name: Publish CLI App

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-22.04, macos-12, windows-2022 ]
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1.1.1
        with:
          deno-version: v1.x
      - run: deno compile --allow-read --allow-write --allow-run --output ./build/ymir ./compiler/cli.ts
      - if: ${{ matrix.os == 'macos-12'}}
        run: |
          mv ./build/ymir ./build/ymir-macos
      - if: ${{ matrix.os == 'ubuntu-22.04'}}
        run: |
          mv ./build/ymir ./build/ymir-linux
      - name: Upload binaries to release
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "./build/ymir*"
          tags: true
          overwrite: true
